PROGRAMMER ?= openocd
OPENOCD_ADAPTER_INIT ?= '-c interface ftdi' 
DEBUG_ADAPTER_ID = 

# Comes pre-flashed with bootloader protected, need to clear security on this...
export OPENOCD_PRE_FLASH_CMDS += -c 'at91samd bootloader 0'

include $(RIOTMAKE)/boards/sam0.inc.mk
